### ISSUE TITLE
Hints Suggests to remove

### ISSUE THREAD

**Issue by MateusMPereira** [rafael-figueiredo-alves/DotEnv4Delphi#4]
src/DotEnv4Delphi.pas on line 394 has a local variable declaration (EnvFile) that is never used on local procedure PopulateDictionary generating a Hint on Delphi IDE.

![image](https://github.com/rafael-figueiredo-alves/DotEnv4Delphi/assets/46699311/10329478-8d32-4d6c-ab23-51f16fc11782)

**Comment by rafael-figueiredo-alves** [comment]
@MateusMPereira, thanks a lot for your help. I haven't noticed that. I'll be correcting it.

**Comment by rafael-figueiredo-alves** [comment]
#5 => This release fixes what you've pointed out. Thanks again.
